"""``idamesh install`` — deploy the GUI plugin loader and the worker launch spec.

Two small files are written so a live IDA can host the idamesh MCP endpoint and the
supervisor's spawned workers can find the interpreter and source tree:

1. A **plugin loader stub** in IDA's user *plugins* directory
   (``{ida_user_dir}/plugins/idamesh_plugin.py``). IDA loads any module there that
   exposes ``PLUGIN_ENTRY``; the stub puts the idamesh source tree on ``sys.path``
   and re-exports the real entry point from
   :mod:`idamesh.bootstrap.plugin_main`. It is authored fresh here.
2. A **launch spec** (``{ida_user_dir}/mcp/launch.json``) recording the ``python``
   interpreter and ``src`` path the auto-launched supervisor should use, plus its
   default endpoint. It is informational/config — the runtimes still work without
   it, but it lets a symlinked dev checkout resolve deterministically.

The path-writing is a pure function (:func:`install_files`) so it is unit-testable
against a temp directory with no IDA present. The base user dir defaults to
:func:`idamesh.infrastructure.discovery.registry.ida_user_dir` (env-overridable),
so ``install`` needs no IDA either.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Sequence

from idamesh.bootstrap.plugin_main import (
    DEFAULT_SUPERVISOR_HOST,
    DEFAULT_SUPERVISOR_PORT,
    SUPERVISOR_MODULE,
)
from idamesh.infrastructure.discovery.registry import ida_user_dir

#: Filename of the loader stub dropped into the IDA plugins dir.
LOADER_FILENAME = "idamesh_plugin.py"
#: Filename of the launch spec under ``{ida_user_dir}/mcp``.
LAUNCH_SPEC_FILENAME = "launch.json"

#: The loader stub written into IDA's plugins dir. Authored fresh for idamesh — it
#: is a thin shim that only fixes ``sys.path`` and re-exports the real entry point.
_LOADER_TEMPLATE = '''\
"""idamesh GUI plugin loader (generated by `idamesh install`).

IDA loads any module in its user plugins directory that defines ``PLUGIN_ENTRY``.
This shim adds the idamesh source tree to ``sys.path`` and re-exports the real
plugin entry point from ``idamesh.bootstrap.plugin_main``. Regenerate it with
``idamesh install`` after moving the checkout.
"""

import sys

_SRC = {src!r}
if _SRC and _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from idamesh.bootstrap.plugin_main import PLUGIN_ENTRY  # noqa: E402,F401
'''


def default_src() -> str:
    """The directory that contains the importable ``idamesh`` package (``…/src``)."""
    import idamesh

    return str(Path(idamesh.__file__).resolve().parent.parent)


def install_files(
    *,
    user_dir: Path,
    plugins_dir: Optional[Path] = None,
    python: str,
    src: str,
    host: str = DEFAULT_SUPERVISOR_HOST,
    port: int = DEFAULT_SUPERVISOR_PORT,
    force: bool = False,
) -> dict:
    """Write the loader stub and launch spec; return the paths written.

    ``plugins_dir`` defaults to ``{user_dir}/plugins``. When ``force`` is false an
    existing loader stub is left untouched (its path is still reported, tagged
    ``skipped``); the launch spec is always rewritten (it is generated config).
    Directories are created as needed. Pure filesystem work — no IDA import.
    """
    user_dir = Path(user_dir)
    plugins_dir = Path(plugins_dir) if plugins_dir is not None else user_dir / "plugins"
    mcp_dir = user_dir / "mcp"
    plugins_dir.mkdir(parents=True, exist_ok=True)
    mcp_dir.mkdir(parents=True, exist_ok=True)

    loader_path = plugins_dir / LOADER_FILENAME
    loader_written = True
    if loader_path.exists() and not force:
        loader_written = False
    else:
        loader_path.write_text(_LOADER_TEMPLATE.format(src=src), encoding="utf-8")

    launch_path = mcp_dir / LAUNCH_SPEC_FILENAME
    launch_spec = {
        "python": python,
        "src": src,
        "module": SUPERVISOR_MODULE,
        "host": host,
        "port": port,
        "written_at": datetime.now(timezone.utc).isoformat(),
    }
    launch_path.write_text(
        json.dumps(launch_spec, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    return {
        "loader": str(loader_path),
        "loader_written": loader_written,
        "launch_spec": str(launch_path),
        "plugins_dir": str(plugins_dir),
        "user_dir": str(user_dir),
    }


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="idamesh install",
        description="Install the idamesh GUI plugin loader and worker launch spec.",
    )
    parser.add_argument(
        "--user-dir",
        default=None,
        help="IDA user directory to install into (default: the resolved IDA user "
        "dir; env IDA_MCP_USER_DIR / IDAUSR override).",
    )
    parser.add_argument(
        "--plugins-dir",
        default=None,
        help="Override the plugins directory (default: <user-dir>/plugins).",
    )
    parser.add_argument(
        "--python",
        default=None,
        help="Interpreter recorded in the launch spec for spawned workers "
        "(default: this interpreter).",
    )
    parser.add_argument(
        "--src",
        default=None,
        help="idamesh source tree recorded in the loader/launch spec "
        "(default: the directory holding this idamesh package).",
    )
    parser.add_argument(
        "--host", default=DEFAULT_SUPERVISOR_HOST, help="Supervisor host for the launch spec."
    )
    parser.add_argument(
        "--port", type=int, default=DEFAULT_SUPERVISOR_PORT, help="Supervisor port for the launch spec."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing loader stub instead of leaving it in place.",
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Run ``idamesh install``. Returns a process exit code."""
    args = _build_parser().parse_args(list(argv) if argv is not None else None)

    user_dir = Path(args.user_dir) if args.user_dir else ida_user_dir()
    plugins_dir = Path(args.plugins_dir) if args.plugins_dir else None
    python = args.python or sys.executable
    src = args.src or default_src()

    try:
        result = install_files(
            user_dir=user_dir,
            plugins_dir=plugins_dir,
            python=python,
            src=src,
            host=args.host,
            port=args.port,
            force=args.force,
        )
    except OSError as exc:
        sys.stderr.write(f"install: failed to write files: {exc}\n")
        return 2

    loader_note = "wrote" if result["loader_written"] else "kept existing"
    sys.stderr.write(
        "idamesh installed:\n"
        f"  plugin loader ({loader_note}): {result['loader']}\n"
        f"  launch spec:                 {result['launch_spec']}\n"
        "Restart IDA to load the plugin (Edit > Plugins is hidden; it is resident).\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
